language: go
go:
  - "1.14"
env:
  - GO111MODULE=on
deploy:
  app: grocerytime
  provider: heroku
  api_key:
    secure: aW+t+vKrQv7mMVBdvR7fOS29DagCD/yv3v+csshrNXlXVMLtUv0gr5BgDmRBvKvjMiCtYDg4L98Ng7nasAO5KXr36NxuNobwXJriTqoM1eqGVHkit9nhz7KBk7aUoilFEikBLF3K9FHYZOHkhO39zj1YnT6Qq/9Cia2/FbZC0jpKWvvIeoz3vxHdnp0u2oufTC6ldKcvAQGYx9rjBgWQ3lynFeyAeg689Yhg1zcNXcyp5z85m9YCxlGkkZsJLfP5qcPrnZQKj6wmLTvT6FRhPAFDOA+ZggLvD7FVemje7/EEvkzpguyM5iCS3lREUnK4k7dM/Wf7lSJ5zxfiRs5MxthCJrvwBCfY02SjRT9PvYVDd6d2Xbgzh5FonKG5pY9Pd1R7E1Gau12MOz5RdM1rQjHE3B0g/Ei6PLhkr1eoZB3w1n7wWOs01RudClfoN3kp1PbS70oFuYVEBnc/2rQIOgyQZyxBGse4Igh7Y363S/2te7CtQe0WqibSVm1pJZIMc6RdTef6u6kZ32CBGw4N1i/r/cw0jCh6tkVZ42fX8ux28JXZVYRWo+p5Q0E+kfS2d05EMNW6J08bV8rVauqj/6uS1jNRTUxU2Q8+d5n0FL/+w9uxxxojYzOEgG7KjzLJJdunmZhvfWRZPkSK/VIHrTFxKZfFhM4DOCCHCHGgsl0=
